# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emb.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'emb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\temb.proto\x12\nprotobuffs\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32P\n\x08\x45mbedder\x12\x44\n\x05\x45mbed\x12\x1c.protobuffs.EmbeddingRequest\x1a\x1d.protobuffs.EmbeddingResponseB\x1bZ\x19./internals/go_protobuffsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031./internals/go_protobuffs'
  _globals['_EMBEDDINGREQUEST']._serialized_start=25
  _globals['_EMBEDDINGREQUEST']._serialized_end=57
  _globals['_EMBEDDINGRESPONSE']._serialized_start=59
  _globals['_EMBEDDINGRESPONSE']._serialized_end=97
  _globals['_EMBEDDER']._serialized_start=99
  _globals['_EMBEDDER']._serialized_end=179
# @@protoc_insertion_point(module_scope)
